
# Support for Docker Compose v2, https://docs.docker.com/compose/overview/
version: '2'
services:
  vsplunk:
    image: busybox
    volumes:
      # - /opt/splunk/etc
      - /opt/splunk/var
  splunkbox:
    #build: .
    hostname: splunkbox
    image: jahshuah/splunk:6.6.1
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    volumes_from:
      - vsplunk
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
